export enum ConversationState {
  IDLE,
  LISTENING,
  PROCESSING,
  SPEAKING,
  BREATHING,
  DISPLAYING_CARD,
  SHOWING_MAP,
  SHOWING_PLACES_LIST,
  SHOWING_LIVE_MAP,
  SHOWING_EMERGENCY_CONTACTS,
}